FROM caddy:2.11.0-beta.2-builder AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/caddyserver/zerossl

FROM caddy:2.11.0-beta.2-builder-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy